# Site settings
title: IMEDEA-AP-LAB
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  IMEDEA-AP Laboratory website
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imedea-ap-lab.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
