# Site settings
title: IMEDEA-AP Oceanography Lab
email: your-email@imedea.uib-csic.es
description: >- # this means to ignore newlines until "baseurl:"
  Mediterranean Institute for Advanced Studies - Physical Oceanography Laboratory
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imedea-ap-lab.github.io" # the base hostname & protocol for your site

# Research focus
research_focus: "Physical Oceanography, Marine Sciences, Mediterranean Sea Research"

# Build settings
markdown: kramdown
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - .git/
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
